version: '3'
name: magnetdirectory
services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

  apiserver:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - mysql
    env_file:
      - ./.env  
    networks:
      - mynetwork
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - apiserver
    networks:
      - mynetwork
    restart: always

  adminer:
    image: adminer
    ports:
      - "9090:8080"
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:

volumes:
  mysql-data: